import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Layout from "@/components/Layout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Reaction - quiz</title>
        <link rel="icon" type="image/x-con" href="https://i0.wp.com/www.reaction-club.com/wp-content/uploads/2021/05/cropped-cropped-logo-reaction-bird.png?fit=32%2C32&ssl=1" />
      </head>
      <body className={poppins.className}>
        <main className="max-w-[400px] mx-auto p-4">
          <Layout>
            <Header/>
            {children}
          </Layout>
        </main>
      </body>
    </html>
  );
}
